export const selectors = {
  emailSelector: "input[id=email]",
  passwordSelector: "input[id=password]",
  joblistSelector: "div[class=misrotList]",
  sendApplicationButton: ".SaveButton",
  applicationLetterSelector: "textarea[id=letter]",
  jobMasterThreeTimesSentBlockSelector: "div[id=modal_content]",
  jobMasterModalCloseBtnSelector: "span[id=modal_closebtn]",
  jobTitleSelector: "div[class=jobHead__text__titleAndCompName]",
  jobLocationSelector: "li[class=jobLocation]",
  jobTypeSelector: "li[class=jobLocation]",
  jobSalarySelector: "li[class=jobSalary]",
  jobDescriptionSelector: "div[class=jobDescription]",
  jobRequirementsSelector: "div[class=jobRequirements]",
  extraFormQuestions: ".FilterQuestions",
};
