export const generalWebSelectors = {
  textSelectors: {
    names: {
      firstNameSelectors: ["First Name", "First name", "first name", "name"],
      lastNameSelectors: ["Last Name", "Last name", "last name", "name"],
      fullNameSelectors: ["Full Name", "Full name", "fullname", "name"],
    },
    emailSelectors: [
      "email",
      "Email",
      "email address",
      "Email address",
      "Email Address",
    ],
    phoneSelectors: [
      "phone",
      "mobile",
      "mobile phone",
      "Mobile phone",
      "Mobile Phone",
      "Phone",
      "phone number",
      "Phone number",
      "Phone Number",
      "Mobile Number",
      "Mobile number",
      "mobile number",
      "mobile phone number",
      "mobile Phone Number",
      "Mobile phone number",
    ],
    githubSelectors: [
      "add link",
      "Add Link",
      "Add link",
      "Github",
      "gitHub",
      "github",
      "showcast",
      "showCast",
      "ShowCast",
      "Website",
      "website",
    ],
    linkedInSelectors: ["linkedIn", "LinkedIn"],
    resumeSelectors: [
      "Attach CV",
      "CV",
      "Resume",
      "attach CV",
      "Attach cv",
      "attach cv",
      "resume",
      "Attach Resume",
      "attach resume",
    ],
  },
};
